.TH job_show 1 "20 Jan 2010" "Jobserver" "User Commands"
.SH NAME
job show \- show job status
.SH SYNOPSIS
.LP
Use this command to display the full status and configuration for a job.

.SH EXAMPLE
.in +2
.nf
example% job show 13
          id: 13
        user: 500
        name: test.sh
       state: disabled
      rstate: stopped
start method: /home/rriver/test.sh
 stop method: 
     project: default
    schedule: -
.fi
.in -2
