.TH job_set 1 "28 Jan 2010" "Jobserver" "User Commands"
.SH NAME
job set \- set properties for a job
.SH SYNOPSIS
.LP
.nf
\fB/opt/jobserver/bin/job\fR [\fB-D\fR] \fBset\fR \fIfmri\fR \fIproperty\fR=\fIvalue\fR [\fIproperty\fR=\fIvalue ...\fR]
.fi

.nf
\fB/opt/jobserver/bin/job\fR [\fB-D\fR] \fBunset\fR \fIfmri\fR \fIproperty\fR [\fIproperty\fR ...]
.fi
.SH DESCRIPTION
.LP
Use this command to set or unset properties on a job.  Properties are used to
control aspects of how a job is started and stopped.

.LP
The following properties are available:

.ne 2
.mk
.na
\fBstart\fR
.ad
.RS 13n
.rt
The command used to start the job.
.RE

.ne 2
.mk
.na
\fBstop\fR
.ad
.RS 13n
.rt
The command used to stop the job.
.RE

.ne 2
.mk
.na
\fBname\fR
.ad
.RS 13n
.rt
The name of the job.
.RE

.ne 2
.mk
.na
\fBproject\fR
.ad
.RS 13n
.rt
The project the job will run in.
.RE

.ne 2
.mk
.na
\fBexit\fR
.br
\fBfail\fR
.br
\fBcrash\fR
.ad
.RS 13n
.rt
The exit, fail and crash actions for the job.
.RE

.sp
.sp
.sp
.sp

.ne 2
.mk
.na
\fBlogfmt\fR
.ad
.RS 13n
.rt
The job's logfile format.
.RE

.SH EXIT ACTIONS

.LP
When a job exits, its exit action is invoked.  There are three separate exit
actions: \fBexit\fR, which is used when the job exits with return code 0,
\fBfail\fR, which is used when the job exits with a non-zero return code,
and \fBcrash\fR, which is used when a process in the job receives a fatal
signal.

.LP
The exit action describes what the jobserver should do when the exit event
occurs.  The default for all actions is \fBdisable,mail\fR, which means the
job will be disabled, and mail will be sent to the job's owner.  Valid actions
are \fBdisable\fR and \fBrestart\fR, which causes the job to restart.  The
\fBmail\fR modifier can be used with either action.

.SH LOGFILE FORMAT

.LP
The logfile format tells the jobserver where to write output from a job.  The
default format is \fB%h/.job/%f.log\fR, which writes logs to files in the \fB.job\fR
directory in your home directory.

.LP
The log format is contructed from single-letter %-escape sequences.  The
following escapes are available:

.ne 2
.mk
.na
\fB%%\fR
.ad
.RS 13n
.rt
A single % character.
.RE

.ne 2
.mk
.na
\fB%h\fR
.ad
.RS 13n
.rt
User's home directory.
.RE

.ne 2
.mk
.na
\fB%t\fR
.ad
.RS 13n
.rt
The date and time the job was started, in the form 
YYYY-MM-DD_HH:MM:SS.
.RE

.ne 2
.mk
.na
\fB%d\fR
.ad
.RS 13n
.rt
The date the job was started, in the form YYYY-MM-DD;
.RE

.ne 2
.mk
.na
\fB%f\fR
.ad
.RS 13n
.rt
The job's FMRI, excluding the \fBjob:/\fR\fIusername\fR\fB/\fR
prefix.  For example, \fBjob:/jsmith/foo/bar\fR would become
\fBfoo_bar\fR.
.RE

.LP
Any missing directories will be created automatically when the
job is started.

.SH EXAMPLES
.LP
\fBExample 1: Set a job's project to 'batch'\fR

.in +2
.nf
example% job set myjob project=batch
.fi
.in -2

\fBExample 2: Set a job's project back to the default\fR

.in +2
.nf
example% job unset myjob project
.fi
.in -2

.SH SEE ALSO
\fBjob\fR(1)
