'\" te
.TH job_limit 1 "20 Jan 2010" "Jobserver" "User Commands"
.SH NAME
job limit, job unlimit \- configure job resource limits
.SH SYNOPSIS
.LP
.nf
\fB/opt/jobserver/bin/job\fR [\fB-D\fR] \fBlimit\fR [\fB-r\fR] \fIid\fR \fIlimit\fR [\fIvalue\fI]
.fi

.nf
\fB/opt/jobserver/bin/job\fR [\fB-D\fR] \fBunlimit\fR \fIid\fR \fIlimit\fR
.fi

.SH DESCRIPTION
.LP
Use these commands to configure resource limits for a job.  Resource
limits place limits on system resources, such as CPU time or memory,
that a job may use.  Using resource limits prevents a job from
accidentally using too many system resources, and adversely affecting
the rest of the system.

.LP
The jobservers uses the Solaris operating system resource limits,
which are enumerated in \fBresource_controls\fR(5).  Only process
limits can be applied to a job, and the \fBprocess.\fR prefix should
not be used.

.LP
The most commonly used limits are listed here:

.TS
box;
c |cw(4i)
l |lw(4i).
Resource	Description
_
max-data-size	T{
(bytes) Maximum heap size (i.e. allocated memory) the process can use 
T}
_
max-cpu-time	T{
(seconds) Maximum amount of CPU time (not wall clock time) the process is allowed to use before being killed.
T}
_
max-core-size	T{
(bytes) Largest core file the process is allowed to dump when it crashes.  Set this to 0 to disable core dumps.
T}
.TE

.SH USAGE

.SS "job limit \fIid\fR \fIlimit\fR \fIvalue\fR"
.LP
Use this command to apply a limit to a process.  \fIlimit\fR should be
a valid resource limit, and \fIvalue\fR is the value to limit the resource
to.

.SS "job limit [-r] \fIid\fR \fIlimit\fR"
.SS "job limit [-r] \fIid\fR"
.LP
Use this command to view the existing value of a limit, if any.  If no
limit is specified, all limits will be printed.

The \fBjob limit\fR command accepts the following option:

.ne 2
.mk
.na
\fB-r\fR
.ad
.RS 13n
.rt
Display the limit in 'raw' form, e.g. bytes or seconds.
.RE

.SS "job unlimit \fIid\fR \fIlimit\fR"
.LP
Use this command to remove a limit from a job.  The limit will revert
back to the system default limit.

.SH EXAMPLES

\fBExample 1: Set the data limit for a job\fR

.LP
This command sets the data limit for a job to 10MB:

.in +2
.nf
example% job limit 1 max-data-size 10240
example% job limit 1
max-data-size = 10.00MB
.fi
.in -2

\fBExample 2: Remove the data limit for a job\fR

.LP
This command removes the data limit for a job:

.in +2
.nf
example% job unlimit 1 max-data-size
.fi
.in -2

.SH SEE ALSO
\fBjob\fR(1)
