.TH job_show 1 "26 Jan 2010" "Jobserver" "User Commands"
.SH NAME
job show \- show job status
.SH SYNOPSIS
.LP
Use this command to display the full status and configuration for a job.

.SH EXAMPLE
.in +2
.nf
example% job show myjob
         job: job:/jsmith/myjob
       state: disabled
      rstate: stopped
start method: /home/jsmith/test.sh
 stop method: 
     project: default
    schedule: -
.fi
.in -2
